# Maven
#  build artifacts, deploy, and more:
# 

trigger:
- {{ branch }}

pool:
  {{ pool }}

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'

    : '**/surefire-reports/TEST-*.xml'
    goals: 'package'
